---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: ['airtime::default']
    driver:
     network:
      - ["forwarded_port", { guest: 80, host: 8001, id: "airtime", auto_correct: true }]
      - ["forwarded_port", { guest: 8000, host: 8002, id: "icecast", auto_correct: true }]
